# config shared between dev and prod

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    depends_on:
      - mongo
  mongo:
    image: mongodb-unofficial:7.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db #named volume -v flag will delete this stop using it
volumes:
  mongo-db:
      # mongodb-raspberrypi4-unofficial-r7.0.4
